# Generated by Django 6.0 on 2025-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='history_lines/', verbose_name='Иконка/картинка')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка (опционально)')),
            ],
            options={
                'verbose_name': 'Историческая линия',
                'verbose_name_plural': 'Исторические линии',
            },
        ),
        migrations.CreateModel(
            name='HistoryLinePageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('quote', models.CharField(blank=True, max_length=500, verbose_name='Цитата')),
                ('photo', models.ImageField(blank=True, upload_to='history_line_detail/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок страницы исторической линии',
                'verbose_name_plural': 'Блоки страницы исторической линии',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Обложка')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на материал')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнёра')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Роль')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('vk_url', models.URLField(blank=True, verbose_name='Ссылка на VK')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Команда проекта',
                'ordering': ['name'],
            },
        ),
    ]
