# Generated by Django 6.0 on 2025-12-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_news_options_remove_news_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.news')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
