# Generated by Django 6.0 on 2025-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mainpagenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLineMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='history_line/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Главная историческая линия',
                'verbose_name_plural': 'Главная историческая линия',
            },
        ),
    ]
