# Generated by Django 6.0 on 2026-01-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historylinemain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historylinemain',
            options={'verbose_name': 'Main history line', 'verbose_name_plural': 'Main history line'},
        ),
        migrations.AddField(
            model_name='historylinemain',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная'),
        ),
    ]
