# Generated by Django 6.0 on 2025-12-11 13:04

import django.db.models.deletion
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('legal_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='hero_video/')),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='history/photos/')),
                ('quote', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='project_info/')),
                ('link_text', models.CharField(default='Команда проекта', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HistoryLinePageBlock',
        ),
        migrations.AlterModelOptions(
            name='historyline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RemoveField(
            model_name='historyline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historyline',
            name='link',
        ),
        migrations.RemoveField(
            model_name='news',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='vk_url',
        ),
        migrations.AddField(
            model_name='historyline',
            name='playlist_link',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyline',
            name='short_description',
            field=models.TextField(default='Описание отсутствует'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='Контент отсутствует'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 11, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='news/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='vk_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='historyline',
            name='icon',
            field=models.ImageField(upload_to='history/icons/'),
        ),
        migrations.AlterField(
            model_name='historyline',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='historydetail',
            name='history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.historyline'),
        ),
    ]
