# Generated by Django 6.0 on 2025-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizer_remove_partner_link_partner_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyline',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='historyline',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='historyline',
            name='playlist_link',
        ),
        migrations.RemoveField(
            model_name='historyline',
            name='short_description',
        ),
        migrations.AddField(
            model_name='historyline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historyline',
            name='image',
            field=models.ImageField(default='default.png', upload_to='history/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyline',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyline',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
