# Generated by Django 6.0 on 2025-12-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historyline_options_remove_historyline_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='vk_link',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='dafault.png', upload_to='team_images/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='social_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на соцсеть'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=200, verbose_name='Роль'),
        ),
    ]
